# Generated by Django 5.0.1 on 2024-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('practice_area', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('langue', models.CharField(default='arab', max_length=10)),
                ('experiance', models.TextField(blank=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
